### ISSUE TITLE
Problems Importing .OVF

### ISSUE THREAD

**Issue by darrenmartyn** [HyperionGray/whobuntu#2]
So on latest OSX, using VirtualBox 6.0.6 r130049, the whobuntu .ovf file refuses to import, from either CLI (`VBoxManage import ~/Downloads/whobuntu-0.0.1alpha.ovf`), or via the GUI import tool - from CLI it just "hangs" at 0% forever, spinning the VBoxSVC process, and from GUI it just hangs. Other appliances (f.ex: the Whonix ones) import just fine.

The hashes match up, so its not a corrupted download. Was wondering if maybe there was an issue with the exported appliance or something?

**Comment by acaceres2176** [comment]
hmm i'll do some testing here and see if I can reproduce! I'll also be releasing a 64-bit version soon. Can anyone else confirm this bug?

**Comment by darrenmartyn** [comment]
Just downloaded the file again using `wget` (previously had downloaded it using Brave (browser)), after realising the file *somehow* got renamed from .ova to .ovf. File hashes still match just fine, and now the import works fine - provided the extension is "ova".

I guess VirtualBox uses the extension for something and gets confused? What I don't get is why the fuck Brave on OSX caused the extension to be changed on download.

Filing this under "My browser did what?!" and "Apparently file extensions really matter for VirtualBox".
